require.config({
	baseUrl: 'js',
	paths: {
				
    	"Modernizr":'vendor/modernizr',
		"jquery":'vendor/jquery',
		"fastclick":'vendor/fastclick',
    	"foundation": 'foundation/foundation',
    	"jquery.cookie": 'vendor/jquery.cookie',
    	"foundation.abide": 'foundation/foundation/foundation.abide',
    	"foundation.accordion": 'foundation/foundation.accordion',
    	"foundation.alert": 'foundation/foundation.alert',
    	"foundation.clearing": 'foundation/foundation.clearing',
    	"foundation.dropdown": 'foundation/foundation.dropdown',
    	"foundation.equalizer": 'foundation/foundation.equalizer',
    	"foundation.interchange": 'foundation/foundation.interchange',
    	"foundation.joyride": 'foundation/foundation.joyride',
    	"foundation.magellan": 'foundation/foundation.magellan',
    	"foundation.offcanvas": 'foundation/foundation.offcanvas',
    	"foundation.orbit": 'foundation/foundation.orbit',
    	"foundation.reveal": 'foundation/foundation.reveal',
    	"foundation.slider": 'foundation/foundation.slider',
    	"foundation.tab": 'foundation/foundation.tab',
    	"foundation.toolbar": 'foundation/foundation.toolbar',
    	"foundation.topbar": 'foundation/foundation.topbar',
  },
	shim:{
	'Modernizr': {
            exports: 'Modernizr'
    },
	"foundation": ['jquery'],
	"jquery.cookie": ['jquery'],
    "foundation.abide": ['foundation'],
    "foundation.accordion": ['foundation'],
    "foundation.alert": ['foundation'],
    "foundation.clearing": ['foundation'],
    "foundation.dropdown": ['foundation'],
    "foundation.equalizer": ['foundation'],
    "foundation.interchange": ['foundation'],
    "foundation.joyride": ['foundation', 'jquery.cookie'],
    "foundation.magellan": ['foundation'],
    "foundation.offcanvas": ['foundation'],
    "foundation.orbit": ['foundation'],
    "foundation.reveal": ['foundation'],
    "foundation.slider": ['foundation'],
    "foundation.tab": ['foundation'],
    "foundation.toolbar": ['foundation'],
    "foundation.topbar": ['foundation']
	},
});